# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b13d4be4e3ccc3968cd12617be5f32cd381fd48c1648040e0c3f791d373fa3097e0dbba4895e5006f7c46288e8608f7bc20cb9dc52f55e7404e5f7f4b64c0f78

test:
  secret_key_base: ca4f7ebf64b65916e1188dad3009520f1f38e26e976b28d18e836afa38353877f3c7f225cf3badd4f11321d7e3bcf3b0162549079ce46682f55dba92c7532ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
